#! /bin/bash

for filedev in $(ls *.h) $(ls *.c)
do
 ci $filedev
done
for filedev in $(ls *.h,v) $(ls *.c,v)
do
 co $filedev
done
insertdriver()
{
read -n1 -p "Do you want to insert driver?(y/n)"
if [ $REPLY = 'y' ]
then
	insmod ./modules/Abhijeet_mod.ko
	read
	lsmod
	read
	cat /proc/modules
	read
	cat /proc/devices
	read
	dmesg
fi
}
remdriver()
{
read -n1 -p "Do you want to remove driver?(y/n)"
if [ $REPLY = 'y' ]
then
	rmmod Abhijeet_mod
	read
	lsmod
	read
	cat /proc/modules
	read
	cat /proc/devices
	read
	dmesg
fi
}
if make
then 
   insertdriver
   remdriver
fi
read -n1 -p "Do you want to edit driver?(y/n)"
if [ $REPLY = 'y' ]
then
	for filedev in $(ls *.h,v) $(ls *.c,v)
	do
	co -l $filedev
        done
fi
